[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-bosch_new
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-bosch_new
GtkTheme=oomox-bosch_new
MetacityTheme=oomox-bosch_new
IconTheme=oomox-bosch_new
